title: NFSee
lang: zh_CN
description: >
  NFSee is a flutter application running on iOS & Android that can dump data from various types of NFC tags & cards.
baseurl: ""
url: "https://nfsee.nfc.im"
github_username: nfcim

google_verify: 83dtt0A67mWVlunPoi-hOtHyf-eO_85HTHtRgrXm4Vw

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


# google_analytics: 
disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

sidebar:
  - name: 主页
    url: /
  - name: 添加卡片支持
    url: /add-card-support/
  - name: JS 扩展 API
    url: /js-extension/
  - name: 捐赠
    url: /donate/
  - name: 关于
    url: /about/
